### ISSUE TITLE
Compatibility with LGU

### ISSUE THREAD

**Issue by Malcolm-Q** [paul-merkamp/LCBetterSaves#1]
Hi there,

I created a mod called [LateGameUpgrades](https://github.com/Malcolm-Q/LC-LateGameUpgrades). I introduced a custom saving and loading system using json files. All files are named `LGU_x` where x is the save file slot. They exist in the persistent data path alongside the vanilla save files.

After putting this update on thunderstore a lot of users requested compatibility with this mod.

It looks like the easiest path to achieve that is to add a check for the presence of LGU suffixed json files when you do your rearranging and rearrange them so they still align with their vanilla save file. 

If you are receptive to pull requests I could take a crack at adding it in, otherwise if you think this is easy enough to throw in in a couple minutes and want to do it yourself it would be greatly appreciated by me and the users of my mod.

Great work and idea with this mod. 👍

**Comment by paul-merkamp** [comment]
Hi Malcolm, thanks for reaching out!

I'm waist deep in another project for the next 9 days, but I'd be glad to make that tweak afterwards.

I'd also gladly merge in a pull request & put out a new release sooner, if you feel comfortable with writing that.

By the way, I recognize your mod, haven't tried it out yet but it's incredibly intriguing and has been on my list! I think your portable teleporters are the first instance of custom equipment I'd seen, and I was wanting to eventually make a super radar booster mod, but I think the headcams mod actually accomplished a lot of the things I'd had in mind. But I digress.

Thanks again for messaging me! :)
Paul

**Comment by Malcolm-Q** [comment]
Awesome.

I have way too much free time on my hands at the moment so I'll fork figure it out tomorrow.

That's great to hear, it's been a lot of fun to make so I'm glad others enjoy it. If it ever intrigues you enough that you'd want to contribute to it and add items / features you'd be more than welcome to.

Talk soon,
Malcolm
