### ISSUE TITLE
V47 support (Weekly Challenges)

### ISSUE THREAD

**Issue by paul-merkamp** [paul-merkamp/LCBetterSaves#10]
I'll release a new version when V47 comes out to address Weekly Challenges being an added UI component, and possibly more depending on how those saves are handled. I'm unsure how much impact the release will have on this mod, but at the very least, it will make weird stuff happen with the UI for sure.

**Comment by nyctodarkmatter** [comment]
![image_2024-01-09_051437610](https://github.com/paul-merkamp/LCBetterSaves/assets/55568272/8b5e520e-bbaa-4633-a173-0a20a482721d)

It's technically compatible, but definitely causes UI weirdness. Looking forward to an update!

**Comment by paul-merkamp** [comment]
Fixed as part of 1.7.0, releasing soon
