### ISSUE TITLE
Lethal Progression

### ISSUE THREAD

**Issue by Khunkurisu** [paul-merkamp/LCBetterSaves#11]
The mod Lethal Progression's values are being reset when using any version of this mod after 1.4.0.  Reverting to 1.4.0 works fine, and none of the changes in 1.6.0 resolved this, so it seems something between 1.4.0 and 1.5.0+ broke compatibility with most other mods that modify saves, which is certainly problematic.

**Comment by Zalgo404** [comment]
It also sometimes keep LethalProgression's level from another previous save and, no matter if you delete save, create new thunderstorm profile or uninstall and reinstall both lethal company and thunderstore, the data isn't cleared and you recover your level from a random save.

**Comment by Khunkurisu** [comment]
bump... Does this need new info or something?  Any indication that this has been noticed would be appreciated.

**Comment by paul-merkamp** [comment]
Apologies, I kept meaning to come back to this one. I don’t have any experience with Lethal Progression. Can you confirm that this is still an issue as of v47 + LCBetterSaves 1.7.0? If so, I will look at adding support as with LateGameUpgrades

**Comment by paul-merkamp** [comment]
Hi @Khunkurisu, can you confirm the issue for me? I'll close the issue if it's been resolved sometime over the last several mod updates.

**Comment by Khunkurisu** [comment]
Sorry for the wait, winter weather has caused issues.  I’ll be testing things out with just these two mods installed on their latest versions this evening and reporting back.

**Comment by paul-merkamp** [comment]
No worries, thanks for the help

**Comment by Khunkurisu** [comment]
https://github.com/paul-merkamp/LCBetterSaves/assets/17495210/29e4ba3e-76c9-46bc-81e3-2ee8266904e2

In the linked video you can see that I have a single save file, with only a few levels in Lethal Progression.  Exiting back to the main menu and creating a new save, I suddenly have many more levels.  It appears it's loading an existing save for Lethal Progression that was once tied to this slot.  As noted in the original post, this doesn't happen when using v1.4.0 of LCBetterSaves.  On v1.4.0, the save files are properly interacting (e.g. it doesn't load an old, existing save just because the slot # is the same).

If I had to guess without going through the commit differences from 1.4.0's release to when it breaks, I'd say it's a combination of not deleting all of the attached files properly when removing/resorting a save slot and also not having a common indicator between the mods to indicate what file belongs to which save slot.

**Comment by Khunkurisu** [comment]
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/17495210/bbbd1170-b4cd-40de-a010-9a4cc3ebddb7)
Attached image for example of save directory for Lethal Progression.

**Comment by Khunkurisu** [comment]
[Player.log](https://github.com/paul-merkamp/LCBetterSaves/files/13944463/Player.log)
Player.log included in case needed.

**Comment by Khunkurisu** [comment]
If I might suggest something, since this has happened with two relatively popular mods now: You could create a generic method of handling saves from other mods, provide info in the readme about how to make a mod compatible with your save setup, and then it'll be easier to track bugs as the issues go to the mod dev to add compatibility, rather than you having to figure out why every mod with its own savefile doesn't work and adding compatibility afterwards.

**Comment by paul-merkamp** [comment]
Good point. I think I want to encourage other mod authors to embed their save data in the file itself with ES3, it makes things even simpler. I'll work on putting together a doc with some resources for that process.

**Comment by paul-merkamp** [comment]
I've added instructions to the readme, so we can point mod authors to that.
I'll add a note on the relevant issue on LethalProgression.

**Comment by paul-merkamp** [comment]
Closing this issue since we'll just be awaiting support on their end now - here is the relevant issue on LethalProgression
https://github.com/stoneman2/LethalProgression/issues/44
