### ISSUE TITLE
Save order is changing

### ISSUE THREAD

**Issue by alkingshefo** [paul-merkamp/LCBetterSaves#14]
each time i enter the game or go back to hosting page, the save slots are completely different.

**Comment by paul-merkamp** [comment]
Are you still having this issue? Can you elaborate/provide screenshots? Can you share a list of mods you're using?

**Comment by alkingshefo** [comment]
I'm gonna update and check the new version, basically what i had is that every time i open the game the save file order for example File 5 was the one i was playing on with 35 days in, the name changes to File 7 or File 5 it doesn't stay in the same order of creation which makes it very hard to find if i did not change the name of the file.

**Comment by alkingshefo** [comment]
i realized the problem, this happens during renaming of the save files into temps. when they go beyond 10 the order is 1,10,11,12 then 2,3,4,5 i have screenshot from the logs showing why i was facing that problem.
![2](https://github.com/paul-merkamp/LCBetterSaves/assets/49885212/f3f450d2-358d-4882-87da-9f356c70dce3)
![1](https://github.com/paul-merkamp/LCBetterSaves/assets/49885212/af37514f-2399-4215-a5b1-ebcd57a9d163) 
![logs](https://github.com/paul-merkamp/LCBetterSaves/assets/49885212/7618b102-2348-439d-a4d6-4d7c0b82fec5)

**Comment by paul-merkamp** [comment]
Should be fixed now.
