### ISSUE TITLE
Saves are invisible

### ISSUE THREAD

**Issue by SleepyBoyeZZzzZZ** [paul-merkamp/LCBetterSaves#18]
most likely a visual glitch, but regardless when i go to host a file all of my previous save files are now invisible, the only thing being available is the new file button. this isn't inherently a problem since i can just go to the files and delete some but if you create a new file it shows up in the list but you cant see it like the rest

![Screenshot 2024-01-16 113619](https://github.com/paul-merkamp/LCBetterSaves/assets/156837054/e98fb201-8a5d-4e0f-a29a-55503bbaf4a0)

**Comment by tornado-ii** [comment]
Bumping. I have the same issue. 
The saves are all still present in the saves folder, but don't appear in the menu.
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/25275680/03613641-2844-4ad5-8ca0-133d892cdadb)

**Comment by paul-merkamp** [comment]
Looks like my attempt to fix this issue failed. Thanks for the screenshot of your files. Can you share log output when you get the chance?

**Comment by tornado-ii** [comment]
Here is the log file.
[Player.log](https://github.com/paul-merkamp/LCBetterSaves/files/13967535/Player.log)
You'll notice this appears in the log:
> Panel label not found.
> Delete file game object not found.
> Error occurred while refreshing save buttons: Object reference not set to an instance of an object
> Error occurred while updating files panel rect: Failed to find FilesPanel RectTransform.
> An error occurred during initialization: Object reference not set to an instance of an object
> [...]
> Returning week num: 5
> week num: 5
> Positioning based on 9 saves.
> Found file: LCSaveFile0
> Found file: LCSaveFile0Config
> Found file: LCSaveFile1
> Found file: LCSaveFile1Config
> Found file: LCSaveFile2
> Found file: LCSaveFile2Config
> Found file: LCSaveFile3
> Found file: LCSaveFile3Config
> Found file: LCSaveFile4
> Error occurred while refreshing save buttons: Failed to compare two elements in the array.

I believe this is the most relevant part of the output and should lead you to the problem.

**Comment by germ4nic** [comment]
Here to affirm this issue, after tinkering with a few mods I had the same problem occur where my saves were still there but invisible on the file select screen.
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/128669664/e61e5c61-6eda-4f17-aaab-2067d3952500)
also had the same error that the previous person mentioned above appear in my log file.

**Comment by Blazemakara** [comment]
Have the same issue here too.

**Comment by paul-merkamp** [comment]
Fixed with 1.7.3. Please reopen if you encounter this issue with BetterSaves 1.7.3
