### ISSUE TITLE
Suggestion: Selected save file should populate the server name

### ISSUE THREAD

**Issue by tornado-ii** [paul-merkamp/LCBetterSaves#22]
When selecting a save file, it should replace the server name with its name. This way the server will automatically be renamed based on the save file, which can be helpful with certain mod sets or play groups (e.g. solo vs friend group A vs friend group B vs public). 
This action should only occur when _selecting_ a save file. That way the server (and by extension the save itself) can be renamed freely in addition to this functionality.
An alternative approach would be to allow this behaviour only when the server name is currently empty. You would have to ensure renaming save files to empty names disallowed, though.

**Comment by paul-merkamp** [comment]
I understand the concept behind this, but I think implementing it would ultimately create more problems than it would solve, especially considering that renaming saves is also dependent on the server name field. Typing a server name is a brief enough process, even for public server power users.

I think a possible alternate concession could be adding a rename field and keeping that separate from the server name field. But that would be a pretty low priority for me.

I appreciate the idea, though. Thanks for using my mod and caring enough to leave suggestions. :)

**Comment by tornado-ii** [comment]
I still think it could work well, especially for the presented scenarios, but it's definitely something that would require some sort of A/B testing to see how it's received. There's always the cop-out of "make it a config option", but I think it's unnecessary and I understand your decision.

Thank you for making this mod ! I consider it essential and would hope to see it integrated into the base game myself. Looking forward to more !
