### ISSUE TITLE
Overlapping labels in the Save selection.

### ISSUE THREAD

**Issue by syprate** [paul-merkamp/LCBetterSaves#4]
"New File" and a "File 1" label are overlapping in the save selection menu. This is with a fresh install and no other mods installed. The actual "File 1" is displayed below the "New file" as expected and "New File" does function properly, Screenshot attached.

![image](https://github.com/paul-merkamp/LCBetterSaves/assets/79107521/caff51c1-baef-4054-94b6-bd6eca85bc07)

**Comment by syprate** [comment]
I saw you mentioned you were aware of UI issues so this is just documentation to help diagnose whenever you may get to it.

    - Specifically, this happens when there are 4 files and one of them is deleted. Some of the files were named.

**Comment by Lucky-56** [comment]
seems to still be happening while having 2 save files
![saves](https://github.com/paul-merkamp/LCBetterSaves/assets/55949451/4514843a-11b3-4a64-98f2-7d9f22c9ce4d)

also when deleting the second file it says: Do you want to delete File 3?
![sdelete](https://github.com/paul-merkamp/LCBetterSaves/assets/55949451/d3f91d85-adfc-45cf-9773-604b367a476d)
