### ISSUE TITLE
Bug: LC Better Save v1.5.0 fails to register LGU saves, causing purchased upgrades to reset

### ISSUE THREAD

**Issue by FireGeneral** [paul-merkamp/LCBetterSaves#6]
I've never posted here before, so I'll try to make this short.
There's a mod called Lategame Upgrades, and it uses its own save data files which store values of various upgrades.
The save files for that mod usually called "LGU_1", "LGU_2", "LGU_3", etc. (I call them LGU saves)

So, after playing some games with LC Better Save v1.5.0 and LateGame Upgrades v2.6.1, I found that your mod never register any of the LGU saves, instead, it keeps on trying to create new empty LGU saves and renaming the pre-existing ones to LGU_(Number+1).

The issue it creates is "Everytime I close my game and re-open it, I lose all of my upgrades that I've already bought in previous sessions.", effectively wiping huge amount of my progress.

I've already tried manually renaming the LGU saves to match your LC saves, hoping to fix the issue. However, your mod always automatically update those back to their original "mismatched" number when I play the game. 

In the end, I found that downgrading back to LC Better Save v1.4.0 fix the issue as it can correctly read and register LGU saves no problem unlike v1.5.0.

Note: English not my native, sorry for bad English.

**Comment by paul-merkamp** [comment]
@Malcolm-Q this is pretty detailed, might help with your PR?

**Comment by FireGeneral** [comment]
> @Malcolm-Q this is pretty detailed, might help with your PR?
I'm not a PR...
I'm just a user of both mods, encountered a problem with the mods, and wish to have it fixed...

**Comment by FireGeneral** [comment]
> @Malcolm-Q this is pretty detailed, might help with your PR?

I'm not a PR...
I'm just a user of both mods, encountered a problem with the mods, and wish to have it fixed...

**Comment by paul-merkamp** [comment]
That's just me pinging the author of the other mod and telling him this is good info. He's planning on writing code and making a PR (pull request) to resolve this issue.

**Comment by FireGeneral** [comment]
> That's just me pinging the author of the other mod and telling him this is good info. He's planning on writing code and making a PR (pull request) to resolve this issue.

Ohhh... sorry... English not my native :(

**Comment by Malcolm-Q** [comment]
Hey my friend made some changes, tested, and made a pull request. This should be resolved soon. Thanks for the info.

**Comment by paul-merkamp** [comment]
@Malcolm-Q I'm making a push within the next few minutes, could I trouble you to have your friend test and make sure the LGU compatibility they added isn't broken by my changes? I'm not sure what the testing process was & don't want to muck it up

**Comment by Malcolm-Q** [comment]
@paul-merkamp sure thing I'll send him a message thanks for the heads up

**Comment by paul-merkamp** [comment]
presumably fixed in 1.6.0, closing unless problems arise
