### ISSUE TITLE
LGU files seem to be sorted wrongly

### ISSUE THREAD

**Issue by Lucky-56** [paul-merkamp/LCBetterSaves#7]
I don't know if it has an impact in-game, since I haven't tested it but it seems to me thats this may be an issue as the temp files are wrongly sorted
![log](https://github.com/paul-merkamp/LCBetterSaves/assets/55949451/0b015dde-1e52-4ecc-a138-e2f820f0d093)

**Comment by Malcolm-Q** [comment]
Hey, my friend just made a pull request this should be resolved soon.

**Comment by Lucky-56** [comment]
aight gotchu didn't know that was related
