### ISSUE TITLE
Better Saves doesn't load in even though I have it enabled.

### ISSUE THREAD

**Issue by ParaliyzedEvo** [paul-merkamp/LCBetterSaves#9]
Pretty much what the title says. I have the mod enabled but better saves doesn't load in the game. I checked the logs and it says it loads in but in game it doesn't and I only have three save slots like in the base game. Ik it might be a mod compatibility issue and tried testing it but it doesn't help as much because sometimes it works soemtimes it doesn't. I hope you can help!
Modpack: https://thunderstore.io/c/lethal-company/p/Paraliyzed/Pick_Up_the_Sheriff_for_Me_Baby/
Log: [LogOutput.zip](https://github.com/paul-merkamp/LCBetterSaves/files/13756673/LogOutput.zip)
Screenshot: ![image](https://github.com/paul-merkamp/LCBetterSaves/assets/107338855/7acd08d4-5bed-4895-add0-b3b67800fb40)

**Comment by paul-merkamp** [comment]
I'll hazard a guess that it's a compatibility issue with whatever mod is giving you the Crew Size option. Can you send me a link to that mod so I can take a look?

**Comment by paul-merkamp** [comment]
Guessing this is a compatibility issue with MoreSaves, I'll look into it

**Comment by ParaliyzedEvo** [comment]
https://thunderstore.io/c/lethal-company/p/notnotnotswipez/MoreCompany/

**Comment by paul-merkamp** [comment]
yeah, sorry, only saw the attached log after I asked for the link. my bad

**Comment by ParaliyzedEvo** [comment]
All good

**Comment by paul-merkamp** [comment]
Looks okay to me with morecompany installed.

@ParaliyzedEvo **I would recommend trying to load just my mod and make sure it works that way.
Then, if you can narrow it down to whichever mod in the pack that might be causing the issue, I could go in and try to fix the issue.**

Right now, it's not feasible for me to try and figure out which of the 150 mods is causing the problem - especially given the malware stuff that's been happening on Thunderstore.

I'll also release a 1.6.0 soon which fixes some other bugs and might also fix this one alongside it as a happy coincidence.

Closing for now, feel free to either wait and see, or reopen with whichever mod is causing the problem.

**Comment by ParaliyzedEvo** [comment]
@paul-merkamp I found the mod that was causing the issue. Ik you already released 1.6.0 and probably don't want to upload another update but heres the mod that was causing the problem. Idk if you can fix it or not but hope this helps! 
https://thunderstore.io/c/lethal-company/p/Asylud/Glowstick/

**Comment by paul-merkamp** [comment]
@ParaliyzedEvo thanks for the info! I've looked into this; it's unfortunately not something I can fix on my end, and I have no idea how to get into contact with that mod's creator. I've updated the mod's page on Thunderstore to reflect the incompatibility.

**Comment by paul-merkamp** [comment]
https://github.com/paul-merkamp/LCBetterSaves/issues/12
